import { BeatPreset } from '../types';

export const PRESETS: BeatPreset[] = [
  {
    id: 'basic-rock',
    name: 'Basic Rock',
    description: 'Classic rock groove with hi-hat on 8ths, snare on 2 and 4',
    trackAssignments: {
      hihat: 'hh-8ths',
      snare: 'snare-backbeat',
      kick: 'kick-basic-rock',
    },
    limbAssignments: {
      hihat: 'RH',
      snare: 'LH',
      kick: 'RF',
      hihatPedal: 'LF',
      tom1: 'RH',
      tom2: 'LH',
      floorTom: 'LF',
      ride: 'RH',
    },
  },
  {
    id: 'jazz-swing',
    name: 'Jazz Swing',
    description: 'Swing feel with ride cymbal, jazz kick and snare pattern',
    trackAssignments: {
      ride: 'ride-8ths',
      snare: 'snare-backbeat',
      kick: 'kick-basic-rock',
    },
    limbAssignments: {
      hihat: 'none',
      snare: 'LH',
      kick: 'RF',
      hihatPedal: 'LF',
      tom1: 'RH',
      tom2: 'LH',
      floorTom: 'LF',
      ride: 'RH',
    },
  },
  {
    id: 'half-time-shuffle',
    name: 'Half-Time Shuffle',
    description: 'Laid-back shuffle feel common in blues and ballads',
    trackAssignments: {
      hihat: 'hh-shuffle',
      snare: 'snare-backbeat',
      kick: 'kick-4-on-floor',
    },
    limbAssignments: {
      hihat: 'RH',
      snare: 'LH',
      kick: 'RF',
      hihatPedal: 'LF',
      tom1: 'RH',
      tom2: 'LH',
      floorTom: 'LF',
      ride: 'RH',
    },
  },
  {
    id: 'four-on-floor',
    name: 'Four on the Floor',
    description: 'Kick drum on every quarter note, disco/pop feel',
    trackAssignments: {
      hihat: 'hh-8ths',
      snare: 'snare-backbeat',
      kick: 'kick-4-on-floor',
    },
    limbAssignments: {
      hihat: 'RH',
      snare: 'LH',
      kick: 'RF',
      hihatPedal: 'LF',
      tom1: 'RH',
      tom2: 'LH',
      floorTom: 'LF',
      ride: 'RH',
    },
  },
  {
    id: 'pop',
    name: 'Pop Groove',
    description: 'Syncopated kick pattern with steady hi-hat',
    trackAssignments: {
      hihat: 'hh-8ths',
      snare: 'snare-backbeat',
      kick: 'kick-pulse',
    },
    limbAssignments: {
      hihat: 'RH',
      snare: 'LH',
      kick: 'RF',
      hihatPedal: 'LF',
      tom1: 'RH',
      tom2: 'LH',
      floorTom: 'LF',
      ride: 'RH',
    },
  },
  {
    id: 'funk',
    name: 'Funk Groove',
    description: 'Syncopated snare ghost notes, driving kick',
    trackAssignments: {
      hihat: 'hh-8ths',
      snare: 'snare-rocks',
      kick: 'kick-basic-rock',
    },
    limbAssignments: {
      hihat: 'RH',
      snare: 'LH',
      kick: 'RF',
      hihatPedal: 'LF',
      tom1: 'RH',
      tom2: 'LH',
      floorTom: 'LF',
      ride: 'RH',
    },
  },
];